### ISSUE TITLE
Default user and password

### ISSUE THREAD

**Issue by svauchel** [hsxsix/archlinuxarm-aarch64-rpi#1]
Hi,
I've successfuly installed this archlinux image and set wifi access. I can connect via ssh but I'm not able to log in (I've tried alarm/alarm and root/root => acces denied).
Thank you for your help.
Sébastien

**Comment by svauchel** [comment]
I'm able to localy log in with root user, but I can't log in via ssh on another machine. How to permit headless ssh login ?

**Comment by hsxsix** [comment]
> I'm able to localy log in with root user, but I can't log in via ssh on another machine. How to permit headless ssh login ?

sorry, I have not had such a problem.root can login by ssh as well.

**Comment by svauchel** [comment]
My bad, IP address was not the right one.
alarm user can't logs in but it's working with root user.

**Comment by hsxsix** [comment]
> My bad, IP address was not the right one.
> alarm user can't logs in but it's working with root user.
This archlinuxarm system is a basic archlinux system, only has root user, no other users such as 'alarm', you can add an user this command: `useradd -m -G sudo -s /bin/bash alarm`, and set a password for new user: `passwd alarm`
