### ISSUE TITLE
Trying to install base package gives me conflicting files error

### ISSUE THREAD

**Issue by pietrotti97** [hsxsix/archlinuxarm-aarch64-rpi#2]
Trying to install base package via pacman it gives me conflicting files error regarding brcmfmac.
This is the pacman log: 

[root@archlinuxarm ~]# pacman -S base
:: There are 50 members in group base:
:: Repository core
   1) bash  2) bzip2  3) coreutils  4) cryptsetup  5) device-mapper  6) dhcpcd  7) diffutils  8) e2fsprogs  9) file  10) filesystem  11) findutils  12) gawk  13) gcc-libs
   14) gettext  15) glibc  16) grep  17) gzip  18) inetutils  19) iproute2  20) iputils  21) jfsutils  22) less  23) licenses  24) linux-firmware  25) logrotate  26) lvm2
   27) man-db  28) man-pages  29) mdadm  30) nano  31) netctl  32) pacman  33) pacman-mirrorlist  34) pciutils  35) perl  36) procps-ng  37) psmisc  38) reiserfsprogs  39) s-nail
   40) sed  41) shadow  42) sysfsutils  43) systemd-sysvcompat  44) tar  45) texinfo  46) usbutils  47) util-linux  48) vi  49) which  50) xfsprogs

Enter a selection (default=all): 
warning: bash-5.0.009-1 is up to date -- reinstalling
warning: bzip2-1.0.8-2 is up to date -- reinstalling
warning: coreutils-8.31-1 is up to date -- reinstalling
warning: cryptsetup-2.2.0-1 is up to date -- reinstalling
warning: device-mapper-2.02.186-1 is up to date -- reinstalling
warning: dhcpcd-7.2.2-1 is up to date -- reinstalling
warning: diffutils-3.7-1 is up to date -- reinstalling
warning: e2fsprogs-1.45.3-1 is up to date -- reinstalling
warning: file-5.37-2 is up to date -- reinstalling
warning: filesystem-2019.05-2 is up to date -- reinstalling
warning: findutils-4.6.0-4.1 is up to date -- reinstalling
warning: gawk-5.0.1-1 is up to date -- reinstalling
warning: gcc-libs-8.3.0-1 is up to date -- reinstalling
warning: gettext-0.20.1-1 is up to date -- reinstalling
warning: glibc-2.29-1 is up to date -- reinstalling
warning: grep-3.3-1 is up to date -- reinstalling
warning: gzip-1.10-1 is up to date -- reinstalling
warning: inetutils-1.9.4-7 is up to date -- reinstalling
warning: iproute2-5.2.0-1 is up to date -- reinstalling
warning: jfsutils-1.1.15-6 is up to date -- reinstalling
warning: less-551-1 is up to date -- reinstalling
warning: licenses-20181104-1 is up to date -- reinstalling
warning: logrotate-3.15.0-1 is up to date -- reinstalling
warning: lvm2-2.02.186-1 is up to date -- reinstalling
warning: man-db-2.8.7-1 is up to date -- reinstalling
warning: man-pages-5.02-1 is up to date -- reinstalling
warning: mdadm-4.1-1 is up to date -- reinstalling
warning: nano-4.4-1 is up to date -- reinstalling
warning: netctl-1.20-1 is up to date -- reinstalling
warning: pacman-5.1.3-1.1 is up to date -- reinstalling
warning: pacman-mirrorlist-20180903-1 is up to date -- reinstalling
warning: pciutils-3.6.2-1 is up to date -- reinstalling
warning: perl-5.30.0-3.1 is up to date -- reinstalling
warning: procps-ng-3.3.15-1 is up to date -- reinstalling
warning: psmisc-23.2-1 is up to date -- reinstalling
warning: reiserfsprogs-3.6.27-2 is up to date -- reinstalling
warning: s-nail-14.9.15-1 is up to date -- reinstalling
warning: sed-4.7-1 is up to date -- reinstalling
warning: shadow-4.7-2 is up to date -- reinstalling
warning: sysfsutils-2.1.0-10 is up to date -- reinstalling
warning: systemd-sysvcompat-242.84-2 is up to date -- reinstalling
warning: tar-1.32-1 is up to date -- reinstalling
warning: texinfo-6.6-1 is up to date -- reinstalling
warning: usbutils-010-1 is up to date -- reinstalling
warning: util-linux-2.34-3 is up to date -- reinstalling
warning: vi-1:070224-3 is up to date -- reinstalling
warning: which-2.21-3 is up to date -- reinstalling
warning: xfsprogs-4.20.0-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (50) bash-5.0.009-1  bzip2-1.0.8-2  coreutils-8.31-1  cryptsetup-2.2.0-1  device-mapper-2.02.186-1  dhcpcd-7.2.2-1  diffutils-3.7-1  e2fsprogs-1.45.3-1  file-5.37-2
              filesystem-2019.05-2  findutils-4.6.0-4.1  gawk-5.0.1-1  gcc-libs-8.3.0-1  gettext-0.20.1-1  glibc-2.29-1  grep-3.3-1  gzip-1.10-1  inetutils-1.9.4-7
              iproute2-5.2.0-1  iputils-20180629.f6aac8d-4  jfsutils-1.1.15-6  less-551-1  licenses-20181104-1  linux-firmware-20190815.07b925b-1  logrotate-3.15.0-1
              lvm2-2.02.186-1  man-db-2.8.7-1  man-pages-5.02-1  mdadm-4.1-1  nano-4.4-1  netctl-1.20-1  pacman-5.1.3-1.1  pacman-mirrorlist-20180903-1  pciutils-3.6.2-1
              perl-5.30.0-3.1  procps-ng-3.3.15-1  psmisc-23.2-1  reiserfsprogs-3.6.27-2  s-nail-14.9.15-1  sed-4.7-1  shadow-4.7-2  sysfsutils-2.1.0-10
              systemd-sysvcompat-242.84-2  tar-1.32-1  texinfo-6.6-1  usbutils-010-1  util-linux-2.34-3  vi-1:070224-3  which-2.21-3  xfsprogs-4.20.0-2

Total Installed Size:  792.53 MiB
Net Upgrade Size:      465.03 MiB

:: Proceed with installation? [Y/n] 
(50/50) checking keys in keyring                                                                             [#################################################################] 100%
(50/50) checking package integrity                                                                           [#################################################################] 100%
(50/50) loading package files                                                                                [#################################################################] 100%
(50/50) checking for file conflicts                                                                          [#################################################################] 100%
error: failed to commit transaction (conflicting files)
linux-firmware: /usr/lib/firmware/brcm/bcm43xx-0.fw exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/bcm43xx_hdr-0.fw exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43143-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43143.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43236b.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43241b0-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43241b4-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43241b5-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43242a.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4329-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4330-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4334-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43340-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4335-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43362-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4339-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43430-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43430a0-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43455-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4350-pcie.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4350c2-pcie.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4354-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4356-pcie.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4356-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43569.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43570-pcie.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4358-pcie.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43602-pcie.ap.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac43602-pcie.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4366b-pcie.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4371-pcie.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4373-sdio.bin exists in filesystem
linux-firmware: /usr/lib/firmware/brcm/brcmfmac4373.bin exists in filesystem
Errors occurred, no packages were upgraded.

Thankyou

**Comment by hsxsix** [comment]
Don't install linux-firmware and linux-*, The kerne、firmware already installed from [raspberrypi/linux](https://github.com/raspberrypi/linux) and [raspberrypi/firmware](https://github.com/raspberrypi/firmware)

**Comment by pietrotti97** [comment]
ok thankyou.
