### ISSUE TITLE
Kernel information

### ISSUE THREAD

**Issue by pietrotti97** [hsxsix/archlinuxarm-aarch64-rpi#3]
Hello, I saw that the image is still on 4.19 kernel with 64bit support. 
Will this image see any kernel update in the future or is it stuck forever with 4.19 ? 
Is the running kernel the armbian kernel or what? 
Is there any way to update it to mainline ( or something like 5.x )?

Thankyou

**Comment by hsxsix** [comment]
> Hello, I saw that the image is still on 4.19 kernel with 64bit support.
> Will this image see any kernel update in the future or is it stuck forever with 4.19 ?
> Is the running kernel the armbian kernel or what?
> Is there any way to update it to mainline ( or something like 5.x )?
> 
> Thankyou

The image kernel is compiled from [raspberrypi/linux](https://github.com/raspberrypi/linux), default branch is rpi-4.19y, see screenshot:
![Screenshot_2019-09-07_09-40-39](https://user-images.githubusercontent.com/18223109/64468186-069e3380-d154-11e9-91fc-f96fb92c4a2f.png)
if you want update kernel, you can git clone this repository and checkout branch to rpi-5.2y or rpi-5.3y, make and install it , [the kernel building tutorial is here](https://www.raspberrypi.org/documentation/linux/kernel/building.md).
I will try update kernel to rpi-5.13y at the latest next week
